[package]
name = "libturion_source"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
mio = { version = "1.0", features = ["os-poll", "net"] }
rustls = "0.23"
thiserror = "2.0"

[lib]
name = "turion_source"
crate-type = ["cdylib", "lib"]
